apiVersion: ooto.sigs.k8s.io/v1alpha1
kind: Module
metadata:
  name: ice-dkms
spec:
  driverContainer:
    container:
      modprobe:
        moduleName: ice
      kernelMappings:
        - literal: 5.4.196-108.356.amzn2.x86_64
          containerImage: 804517629211.dkr.ecr.eu-west-3.amazonaws.com/ice-kmod:1.6
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            pull:
              insecure: false
            push:
              insecure: false
      
            dockerfile: |
              ARG KERNEL_VERSION=''
              FROM amazonlinux as builder
              RUN amazon-linux-extras install kernel-5.4 -y
              RUN yum install -y kernel-headers-5.4.196-108.356.amzn2.x86_64 kernel-5.4.196-108.356.amzn2.x86_64 kernel-devel-5.4.196-108.356.amzn2.x86_64 install dkms python3 git make gcc bison flex elfutils-libelf-devel openssl-devel xz yum-utils bc && yum clean all
              WORKDIR /usr/src
              RUN curl -L https://sourceforge.net/projects/e1000/files/ice%20stable/1.8.9/ice-1.8.9.tar.gz/download > ice-1.8.9.tar.gz
              RUN tar xfvz ice-1.8.9.tar.gz
              RUN cp -r ice-1.8.9/src/* .
              RUN git clone https://github.com/enriquebelarte/dkms-ooto.git 
              RUN cp dkms-ooto/dkms-ice.conf ice-1.8.9/dkms.conf
              RUN dkms add -m ice -v 1.8.9 && dkms build -m ice -v 1.8.9 dkms install -m ice -v 1.8.9

              FROM amazonlinux 
              RUN yum -y install kmod dkms && yum clean all
              #RUN amazon-linux-extras install kernel-5.4
              ARG KERNEL_VERSION
              RUN mkdir -p /opt/lib/modules/${KERNEL_VERSION}
              COPY --from=builder /build/ice-1.8.9/src/ice.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
    imageRepoSecret: 
      name: aws-ecr   
  selector:  
    kubernetes.io/hostname: ip-192-168-13-20.eu-west-3.compute.internal
