apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: ice 
spec:
  driverContainer:
    container:
      modprobe:
        moduleName: ice
      kernelMappings:
        - literal: 5.15.0-43-generic
          containerImage: quay.io/ebelarte/kmmo-lab:1.0-ice-local-kmod 
          build:
            pull:
              insecure: false
            push:
              insecure: false
            dockerfile: |
              ARG KERNEL_VERSION=''
              FROM ubuntu as builder
              RUN apt-get update && apt-get install -y bc bison flex curl libelf-dev gnupg wget git make bc gcc
              RUN apt-get -y install linux-headers-5.15.0-43-generic
              WORKDIR /usr/src
              RUN curl -L https://sourceforge.net/projects/e1000/files/ice%20stable/1.8.9/ice-1.8.9.tar.gz/download > ice-1.8.9.tar.gz
              RUN tar xfz ice-1.8.9.tar.gz
              WORKDIR /usr/src/ice-1.8.9/src
              RUN make

    
              FROM ubuntu 
              RUN apt-get update && apt-get install -y kmod
              ARG KERNEL_VERSION
              RUN mkdir -p /opt/lib/modules/${KERNEL_VERSION}
              COPY --from=builder /usr/src/ice-1.8.9/src/ice.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt

    imageRepoSecret: 
      name: quay-eb   
  selector:  
    kubernetes.io/hostname: worker1

