apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: ooto-ci-a
spec:
  driverContainer:
    container:
      modprobe:
        moduleName: ooto-ci-a 

      kernelMappings:
      #Matching kernel with this literal will trigger build unless same image and version exists.
        - literal: 5.15.0-43-generic
          containerImage: quay.io/ebelarte/kmmo-lab:1.0-ooto-local-kmod 
          build:
            pull:
              insecure: false
            push:
              insecure: false
            dockerfile: |
              ARG KERNEL_VERSION=''
              FROM ubuntu as builder
              RUN apt-get update && apt-get install -y bc bison flex libelf-dev gnupg wget git make bc gcc
              RUN apt-get -y install linux-headers-5.15.0-43-generic

              WORKDIR /usr/src
              RUN git clone https://github.com/enriquebelarte/ooto-kmod.git


              WORKDIR /usr/src/ooto-kmod
              RUN make 

    
              FROM ubuntu 
              RUN apt-get update && apt-get install -y kmod
              ARG KERNEL_VERSION
              RUN mkdir -p /opt/lib/modules/${KERNEL_VERSION}
              COPY --from=builder /usr/src/ooto-kmod/ooto_ci_a.ko /opt/lib/modules/${KERNEL_VERSION}/
              COPY --from=builder /usr/src/ooto-kmod/ooto_ci_b.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
    imageRepoSecret: 
      name: quay-eb   
  selector:  
    kubernetes.io/hostname: worker2
