apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: ooto-ci-a
spec:
  driverContainer:
    container:
      modprobe:
        moduleName: ooto-ci-a 

      kernelMappings:
        - literal: 5.10.109 
          containerImage: europe-southwest1-docker.pkg.dev/assisted-installer/kmmo-lab/oot-operator:1.0-ootokmod 
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            pull:
              insecure: false
            push:
              insecure: false
              #secrets:
              #- name: build-secret
            dockerfile: |
              ARG KERNEL_VERSION=''
              FROM debian:stable-slim as builder
              RUN apt-get update && apt-get install -y bc bison flex libelf-dev gnupg wget git make bc gcc
              RUN kv=${1:-v"$(uname -r | sed -E 's/\+*$//')"} && wget "https://chromium.googlesource.com/chromiumos/third_party/kernel/+archive/$kv.tar.gz" && mkdir -p /src/kernel && tar xzf "$kv.tar.gz" -C /src/kernel
              WORKDIR /src/kernel
              RUN gunzip < /proc/config.gz > .config
              RUN yes "" | make oldconfig && make prepare && make scripts
              RUN git clone https://github.com/enriquebelarte/ooto-kmod.git


              WORKDIR ooto-kmod
              RUN make -C /src/kernel

    
              FROM debian:stable-slim 
              RUN apt-get update && apt-get install kmod
              ARG KERNEL_VERSION
              RUN mkdir -p /opt/lib/modules/${KERNEL_VERSION}
              COPY --from=builder /src/kernel/ooto-kmod/ooto_ci_a.ko /opt/lib/modules/${KERNEL_VERSION}/
              COPY --from=builder /src/kernel/ooto-kmod/ooto_ci_b.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
    imageRepoSecret: 
      name: aws-ecr   
  selector:  
    kubernetes.io/hostname: gke-kmmo-lab-cluster-default-pool-073f8f9f-d5xl 

